### ISSUE TITLE
Buildsystem improvement

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#147]
The current buildsystem has some issues:
* cmake "Superbuild" is not well suited to building many interdependent projects with potentially complex policies,
* cmake is not well suited to installing python,
* installing python libs to a prefix does not work well,
* mixing python versions is a nightmare.

So, in order to resolve that we should:
* [x] as a stopgap, validate the improved SuberBuild ( !214 ),
* [x] improve PDI in docker experience (see #138 ),
* [ ] use setup.py/distutils to package python libs instead of cmake ( #149 ),
* [ ] integrate PDI in the spack default repository ( #151 ),
* [ ] provide a self-contained PDI distribution using spack ( #150 ).

**Comment by jbigot** [comment]
marked the checklist item **as a stopgap, validate the improved SuberBuild ( !214 ),** as completed

**Comment by jbigot** [comment]
In GitLab by @ksiero on Feb 6, 2020, 09:29

marked the checklist item **improve PDI in docker experience (see #138 )** as completed

**Comment by jbigot** [comment]
closed
