### ISSUE TITLE
Yaml file improvement

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#311]
In GitLab by @ksiero on Feb 11, 2021, 11:37

After discussion with @youldrouis and @jbigot about handling big yaml file, we agreed that to improve handling it we should add following features:
- [ ] #159 - Metadata type definition in data node
- [ ] #310 - Data name as HDF5 like path
- [ ] #309 - Data, metadata and plugins yaml value as a list
- [ ] #80  - Support an include mechanism for PDI config
