### ISSUE TITLE
Voice++/DDC requirements

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#376]
Voice++ is a rewrite from scratch in C++ of VOICE, a Fortran code based on and simplifying Gysela.

DDC is a C++ library designed to rewrite Gysela from scratch in "modern" C++ (C++-17/20) and co-developed with Voice++.

This issue summarize the requirements identified while developing these and the various issues arising.

* [ ] offer a nice C++ API #131 ,
* [ ] support changing the lock status from code without re-sharing #116,
* [ ] support the creation of type templates that match the types provided by the library and can be instantiated multiple times with different parameters #374 ,
* [ ] support creation of types from code instead of from YAML only #116 ,
* [ ] support the creation of array types from strides information istead of subsize/start #375 .
